### PR TITLE
Add basic circleci config

### PR DESCRIPTION
**Pull request by rtburns-jpl**

### CODE REVIEW

**Review by gshiroma — APPROVED** [review]
LGTM. Thank you @rtburns-jpl  for adding this.

**Review by hfattahi — DISMISSED** [review]

**Comment by hfattahi** [comment]
@rtburns-jpl @gshiroma  now that there is unit and workflow test added to develop would you please update this PR accordingly and then merge?

**Comment by rtburns-jpl** [comment]
@gshiroma this pytest command passes locally for me but fails on CI, any ideas?

```
+ docker run --rm -u 0:0 -v /root/project:/mnt -w /mnt -it opera/proteus:beta pytest tests/
^@^@
============================= test session starts ==============================
platform linux -- Python 3.9.12, pytest-7.1.1, pluggy-1.0.0
rootdir: /mnt
collecting ... collected 0 items                                                              

============================ no tests ran in 0.00s =============================
ERROR: file or directory not found: tests/
```

**Comment by gshiroma** [comment]
> @gshiroma this pytest command passes locally for me but fails on CI, any ideas?
> 
> ```
> + docker run --rm -u 0:0 -v /root/project:/mnt -w /mnt -it opera/proteus:beta pytest tests/
> ^@^@
> ============================= test session starts ==============================
> platform linux -- Python 3.9.12, pytest-7.1.1, pluggy-1.0.0
> rootdir: /mnt
> collecting ... collected 0 items                                                              
> 
> ============================ no tests ran in 0.00s =============================
> ERROR: file or directory not found: tests/
> ```

Hi @rtburns-jpl , thank you for working on that. Maybe you need to add the directory where PROTEUS was installed? Since you changed your working directory, you probably need an absolute path. Something like:

```
docker run --rm -u 0:0 -v /root/project:/mnt -w /mnt -it opera/proteus:beta pytest /home/conda/proteus-0.1/tests/
```

**Comment by rtburns-jpl** [comment]
Hmm, using the full absolute path gives the same error unfortunately.

**Comment by gshiroma** [comment]
> Hmm, using the full absolute path gives the same error unfortunately.

Ok, it looks like `tests` was not copied into the Docker container. I'm checking what we need to change in `setup.py` to fix that.

**Comment by rtburns-jpl** [comment]
There is no copying, it's supposed to be mounted via the -v argument and this works fine locally. Something's weird on the CI setup.

**Comment by gshiroma** [comment]
I just updated `setup.py` in your PR to copy `tests` into the Docker as a package. Do you think that makes sense? If so, please rebuild your Docker container and try again. Hopefully, that will fix the issue.

**Comment by gshiroma** [comment]
@rtburns-jpl , I reverted the changes to `setup.py`.

**Comment by rtburns-jpl** [comment]
Okay, dropped the pytest command. Not sure why it passes locally but fails on CI, but we can at least have the CI do a basic build for now as discussed.

**Review by gshiroma — APPROVED** [review]
LGTM. Thank you for this update, @rtburns-jpl . Hopefully, we'll find out why pytest is not working on the CI.

**Review by hfattahi — APPROVED** [review]
Ok let's open an issue for pytest part and merge the basic CI.

**Pull request merged**
