### PR TITLE
Update to DSWx-HLS SAS in preparation for beta delivery

### PR DESCRIPTION
**Pull request by gshiroma**
This PR provides the following updates to the DSWx-HLS SAS in preparation for beta delivery:
- Add script to generate landcover mask (LAND). The script calls the functions `create_landcover_mask` that will be updated once the algorithm to generate the combined mask is defined; 
- Update SAS to save a set of single-band GeoTIFF files rather than a single multi-band GeoTIFF file; 
- Substitute layer name INTR with WTR-1 and INSM with WTR-2';
- Refactor code.

### CODE REVIEW

**Review by collinss-jpl — COMMENTED** [review]
Hi @gshiroma, wanted to let you know that I've been working with this branch a bit in order to get a preview of the new multiple single-band tif outputs, so I can start planning integration with the PGE, and eventually PCM.

I was able to pull down this branch and build a Docker image to test with, but I observed the following that you should be aware of:

* The `setup.py` for the package is not currently including all proteus source files when creating the `dist` directory that is included in the Docker container. See my comment below on the line that should be added.
* Once I got the image built, I tested it with the l30_greenland and s30_louisiana HLS test datasets. The s30_louisiana ran without any issues, but the l30_greenland set produced the following error:

```
$ dswx_hls.py runconfig/sas_runconfig.yaml
Default runconfig file: /home/conda/proteus-0.1/src/proteus/defaults/dswx_hls.yaml
YAML schema: /home/conda/proteus-0.1/src/proteus/schemas/dswx_hls.yaml
Input runconfig file: runconfig/sas_runconfig.yaml
Validating runconfig file: runconfig/sas_runconfig.yaml
HLS thresholds:
     wigt: 0.0124
     awgt: 0.0
     pswt_1_mndwi: -0.44
     pswt_1_nir: 1500
     pswt_1_swir1: 900
     pswt_1_ndvi: 0.7
     pswt_2_mndwi: -0.5
     pswt_2_blue: 1000
     pswt_2_nir: 2500
     pswt_2_swir1: 3000
     pswt_2_swir2: 1000
input HLS files directory: input_dir
input parameters:
    file(s):
        input_dir/HLS.L30.T22VEQ.2021248T143156.v2.0.B01.tif
        input_dir/HLS.L30.T22VEQ.2021248T143156.v2.0.B02.tif
        input_dir/HLS.L30.T22VEQ.2021248T143156.v2.0.B03.tif
        input_dir/HLS.L30.T22VEQ.2021248T143156.v2.0.B04.tif
        input_dir/HLS.L30.T22VEQ.2021248T143156.v2.0.B05.tif
        input_dir/HLS.L30.T22VEQ.2021248T143156.v2.0.B06.tif
        input_dir/HLS.L30.T22VEQ.2021248T143156.v2.0.B07.tif
        input_dir/HLS.L30.T22VEQ.2021248T143156.v2.0.B09.tif
        input_dir/HLS.L30.T22VEQ.2021248T143156.v2.0.B10.tif
        input_dir/HLS.L30.T22VEQ.2021248T143156.v2.0.B11.tif
        input_dir/HLS.L30.T22VEQ.2021248T143156.v2.0.Fmask.tif
        input_dir/HLS.L30.T22VEQ.2021248T143156.v2.0.SAA.tif
        input_dir/HLS.L30.T22VEQ.2021248T143156.v2.0.SZA.tif
        input_dir/HLS.L30.T22VEQ.2021248T143156.v2.0.VAA.tif
        input_dir/HLS.L30.T22VEQ.2021248T143156.v2.0.VZA.tif
    output_file: None
    DEM file: None
    scratch directory: scratch_dir
loading HLS v.2.0 layers:
    blue
    green
    red
    nir
ERROR band nir not found within input file(s)
ERROR could not read file(s): ['input_dir/HLS.L30.T22VEQ.2021248T143156.v2.0.B01.tif', 'input_dir/HLS.L30.T22VEQ.2021248T143156.v2.0.B02.tif', 'input_dir/HLS.L30.T22VEQ.2021248T143156.v2.0.B03.tif', 'input_dir/HLS.L30.T22VEQ.2021248T143156.v2.0.B04.tif', 'input_dir/HLS.L30.T22VEQ.2021248T143156.v2.0.B05.tif', 'input_dir/HLS.L30.T22VEQ.2021248T143156.v2.0.B06.tif', 'input_dir/HLS.L30.T22VEQ.2021248T143156.v2.0.B07.tif', 'input_dir/HLS.L30.T22VEQ.2021248T143156.v2.0.B09.tif', 'input_dir/HLS.L30.T22VEQ.2021248T143156.v2.0.B10.tif', 'input_dir/HLS.L30.T22VEQ.2021248T143156.v2.0.B11.tif', 'input_dir/HLS.L30.T22VEQ.2021248T143156.v2.0.Fmask.tif', 'input_dir/HLS.L30.T22VEQ.2021248T143156.v2.0.SAA.tif', 'input_dir/HLS.L30.T22VEQ.2021248T143156.v2.0.SZA.tif', 'input_dir/HLS.L30.T22VEQ.2021248T143156.v2.0.VAA.tif', 'input_dir/HLS.L30.T22VEQ.2021248T143156.v2.0.VZA.tif']
```

One last question, will https://github.com/opera-adt/PROTEUS/issues/10 be addressed for the beta delivery?

**Comment by gshiroma** [comment]
> > Hi @gshiroma, wanted to let you know that I've been working with this branch a bit in order to get a preview of the new multiple single-band tif outputs, so I can start planning integration with the PGE, and eventually PCM.
> > I was able to pull down this branch and build a Docker image to test with, but I observed the following that you should be aware of:
> > 
> > * The `setup.py` for the package is not currently including all proteus source files when creating the `dist` directory that is included in the Docker container. See my comment below on the line that should be added.
> > * Once I got the image built, I tested it with the l30_greenland and s30_louisiana HLS test datasets. The s30_louisiana ran without any issues, but the l30_greenland set produced the following error:
> > 
> > ```
> > $ dswx_hls.py runconfig/sas_runconfig.yaml
> > Default runconfig file: /home/conda/proteus-0.1/src/proteus/defaults/dswx_hls.yaml
> > YAML schema: /home/conda/proteus-0.1/src/proteus/schemas/dswx_hls.yaml
> > Input runconfig file: runconfig/sas_runconfig.yaml
> > Validating runconfig file: runconfig/sas_runconfig.yaml
> > HLS thresholds:
> >      wigt: 0.0124
> >      awgt: 0.0
> >      pswt_1_mndwi: -0.44
> >      pswt_1_nir: 1500
> >      pswt_1_swir1: 900
> >      pswt_1_ndvi: 0.7
> >      pswt_2_mndwi: -0.5
> >      pswt_2_blue: 1000
> >      pswt_2_nir: 2500
> >      pswt_2_swir1: 3000
> >      pswt_2_swir2: 1000
> > input HLS files directory: input_dir
> > input parameters:
> >     file(s):
> >         input_dir/HLS.L30.T22VEQ.2021248T143156.v2.0.B01.tif
> >         input_dir/HLS.L30.T22VEQ.2021248T143156.v2.0.B02.tif
> >         input_dir/HLS.L30.T22VEQ.2021248T143156.v2.0.B03.tif
> >         input_dir/HLS.L30.T22VEQ.2021248T143156.v2.0.B04.tif
> >         input_dir/HLS.L30.T22VEQ.2021248T143156.v2.0.B05.tif
> >         input_dir/HLS.L30.T22VEQ.2021248T143156.v2.0.B06.tif
> >         input_dir/HLS.L30.T22VEQ.2021248T143156.v2.0.B07.tif
> >         input_dir/HLS.L30.T22VEQ.2021248T143156.v2.0.B09.tif
> >         input_dir/HLS.L30.T22VEQ.2021248T143156.v2.0.B10.tif
> >         input_dir/HLS.L30.T22VEQ.2021248T143156.v2.0.B11.tif
> >         input_dir/HLS.L30.T22VEQ.2021248T143156.v2.0.Fmask.tif
> >         input_dir/HLS.L30.T22VEQ.2021248T143156.v2.0.SAA.tif
> >         input_dir/HLS.L30.T22VEQ.2021248T143156.v2.0.SZA.tif
> >         input_dir/HLS.L30.T22VEQ.2021248T143156.v2.0.VAA.tif
> >         input_dir/HLS.L30.T22VEQ.2021248T143156.v2.0.VZA.tif
> >     output_file: None
> >     DEM file: None
> >     scratch directory: scratch_dir
> > loading HLS v.2.0 layers:
> >     blue
> >     green
> >     red
> >     nir
> > ERROR band nir not found within input file(s)
> > ERROR could not read file(s): ['input_dir/HLS.L30.T22VEQ.2021248T143156.v2.0.B01.tif', 'input_dir/HLS.L30.T22VEQ.2021248T143156.v2.0.B02.tif', 'input_dir/HLS.L30.T22VEQ.2021248T143156.v2.0.B03.tif', 'input_dir/HLS.L30.T22VEQ.2021248T143156.v2.0.B04.tif', 'input_dir/HLS.L30.T22VEQ.2021248T143156.v2.0.B05.tif', 'input_dir/HLS.L30.T22VEQ.2021248T143156.v2.0.B06.tif', 'input_dir/HLS.L30.T22VEQ.2021248T143156.v2.0.B07.tif', 'input_dir/HLS.L30.T22VEQ.2021248T143156.v2.0.B09.tif', 'input_dir/HLS.L30.T22VEQ.2021248T143156.v2.0.B10.tif', 'input_dir/HLS.L30.T22VEQ.2021248T143156.v2.0.B11.tif', 'input_dir/HLS.L30.T22VEQ.2021248T143156.v2.0.Fmask.tif', 'input_dir/HLS.L30.T22VEQ.2021248T143156.v2.0.SAA.tif', 'input_dir/HLS.L30.T22VEQ.2021248T143156.v2.0.SZA.tif', 'input_dir/HLS.L30.T22VEQ.2021248T143156.v2.0.VAA.tif', 'input_dir/HLS.L30.T22VEQ.2021248T143156.v2.0.VZA.tif']
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > One last question, will #10 be addressed for the beta delivery?
> 
> Thank you so much for your comments, @collinss-jpl . They are very helpful. I updated `setup.py` accordingly.
> 
> In regards to the error message that you pointed out "ERROR band nir not found within input file(s)". That should have been fixed in previous commits (before today's commits). For that version, the DEM was not optional and I noticed that you didn't provide a DEM: `DEM file: None`. Is that possible that your environment is using an older installation/commit of this repo?
> 
> In any case, I pushed new commits, and I made the DEM optional again. Hopefully, this will fix the issue.

In regards to #10, I'm not sure yet if I'll be able to address that issue for beta delivery.

**Comment by collinss-jpl** [comment]
> Thank you so much for your comments, @collinss-jpl . They are very helpful. I updated `setup.py` accordingly.
> 
> In regards to the error message that you pointed out "ERROR band nir not found within input file(s)". That should have been fixed in previous commits (before today's commits). For that version, the DEM was not optional and I noticed that you didn't provide a DEM: `DEM file: None`. Is that possible that your environment is using an older installation/commit of this repo?
> 
> In any case, I pushed new commits, and I made the DEM optional again. Hopefully, this will fix the issue.

@gshiroma The version I'm working with is at commit 9d16168ea2fe527dacf0879e4846df2f6262b38e. Note that I did not provide a DEM file with either HLS dataset, but there were no issues running the s30_louisiana set. I will pull down your latest commits and try again though.

Regarding #10, thanks for the update. Perhaps if I can find the time I will put together a PR that takes care of it, since it should be relatively simple to have a single `logger` that provides same formatting for both the output file and the console.

**Comment by gshiroma** [comment]
> > Thank you so much for your comments, @collinss-jpl . They are very helpful. I updated `setup.py` accordingly.
> > In regards to the error message that you pointed out "ERROR band nir not found within input file(s)". That should have been fixed in previous commits (before today's commits). For that version, the DEM was not optional and I noticed that you didn't provide a DEM: `DEM file: None`. Is that possible that your environment is using an older installation/commit of this repo?
> > In any case, I pushed new commits, and I made the DEM optional again. Hopefully, this will fix the issue.
> 
> @gshiroma The version I'm working with is at commit [9d16168](https://github.com/opera-adt/PROTEUS/commit/9d16168ea2fe527dacf0879e4846df2f6262b38e). Note that I did not provide a DEM file with either HLS dataset, but there were no issues running the s30_louisiana set. I will pull down your latest commits and try again though.
> 
> Regarding #10, thanks for the update. Perhaps if I can find the time I will put together a PR that takes care of it, since it should be relatively simple to have a single `logger` that provides same formatting for both the output file and the console.

That makes sense, @collinss-jpl . I pushed a lot of changes yesterday and commit [9d16168](https://github.com/opera-adt/PROTEUS/commit/9d16168ea2fe527dacf0879e4846df2f6262b38e) didn't include the bug fix that I mentioned.

You'l probably need to update your runconfig file to match the new [schema](https://github.com/gshiroma/PROTEUS/blob/update_to_v0.3/src/proteus/schemas/dswx_hls.yaml).

I just noticed that #10 was already addressed and merged to the main branch [here](https://github.com/opera-adt/PROTEUS/blob/02135a39d9299eb73689607d9a869f684451356d/src/proteus/dswx_hls.py#L1435) so I guess I can close that issue.

**Comment by collinss-jpl** [comment]
Hi @gshiroma and @hfattahi, I ended up tacking some commits onto this PR, since that would be simpler than trying to base changes against the main branch. Hope this is OK. In addition to the new argument, I had to fix a small issue I encountered when I provided a runconfig that was not in same directory location as the input and scratch directories. Let me know what you think.

**Comment by gshiroma** [comment]
Hi @collinss-jpl , thank you for your updates. I appreciate the log and format changes of [b0fe6c6](https://github.com/opera-adt/PROTEUS/pull/15/commits/b0fe6c61d3e20b26658969706a4a3310916e5dc8) and the `setup.py` update of [8562d42](https://github.com/opera-adt/PROTEUS/pull/15/commits/8562d42e508ec012250d4ef1e1799d8a7e6a000b).

In regards to your last commit, [da0023a](https://github.com/opera-adt/PROTEUS/pull/15/commits/da0023a82c510ef9fdbe352c12f25d8bd3a7a975), that change was intentional (commit [1501983](https://github.com/opera-adt/PROTEUS/pull/15/commits/1501983b84d0556eaa63edc8c8ad2ad0fe8b8ebd)). I think it makes more sense for the paths within the runconfig file being relative to that file. Imagine for example the case that the runconfig and input files are in the same directory. We want the code to take the "local" (wrt runcofig) files.

This could also simplify the PGE, as you can put the runconfigs in the same directory as the input files (all in `input_dir`). Or keep them separate (we just need to update your golden dataset runconfig).

Please, let me know your thoughts.

**Comment by gshiroma** [comment]
Hi @collinss-jpl , thank you again for your changes. I temporarily removed changes of commit [da0023a](https://github.com/opera-adt/PROTEUS/pull/15/commits/da0023a82c510ef9fdbe352c12f25d8bd3a7a975). If we decide to go on with that commit, we need to update the [test runconfig](https://github.com/gshiroma/PROTEUS/blob/update_to_v0.3/tests/data/s30_louisiana_mississippi/dswx_hls.yaml).

**Comment by collinss-jpl** [comment]
> Hi @collinss-jpl , thank you again for your changes. I temporarily removed changes of commit [da0023a](https://github.com/opera-adt/PROTEUS/pull/15/commits/da0023a82c510ef9fdbe352c12f25d8bd3a7a975). If we decide to go on with that commit, we need to update the [test runconfig](https://github.com/gshiroma/PROTEUS/blob/update_to_v0.3/tests/data/s30_louisiana_mississippi/dswx_hls.yaml).

Hi @gshiroma, I'm a little bit concerned about the removal of commit [da0023a](https://github.com/opera-adt/PROTEUS/pull/15/commits/da0023a82c510ef9fdbe352c12f25d8bd3a7a975), since it puts an implicit requirement on the runconfig to always be relative to the rest of the PGE/SAS structure. I have no issues with supporting the case where the runconfig and input files are all in the same directory, but I don't think we should necessarily  be *forced* to accommodate that layout.

For example, currently the PGE layer extracts an "isolated" SAS-only version of the runconfig from the full PGE+SAS version. The isolated config is then passed to the SAS main script so the SAS does not need to worry about validating any PGE-specific portions of the config. Currently, the PGE creates this "isolated" version of the Runconfig in the scratch dir, since it's not needed once processing is complete. But with this would mean all other input/output directories would need to go into the scratch dir as well...

I think the main question here, which is a valid one, is **how should relative paths be treated in a RunConfig**? My assumption was that the paths would be relative to the working directory the PGE/SAS is executed from (`/home/conda`), whereas you would prefer paths be relative to the runconfig's location on disk. For the time-being, we can work around this by always specifying absolute paths, but I think we'll need agreement on this pretty soon.

**Comment by gshiroma** [comment]
> > Hi @collinss-jpl , thank you again for your changes. I temporarily removed changes of commit [da0023a](https://github.com/opera-adt/PROTEUS/pull/15/commits/da0023a82c510ef9fdbe352c12f25d8bd3a7a975). If we decide to go on with that commit, we need to update the [test runconfig](https://github.com/gshiroma/PROTEUS/blob/update_to_v0.3/tests/data/s30_louisiana_mississippi/dswx_hls.yaml).
> 
> Hi @gshiroma, I'm a little bit concerned about the removal of commit [da0023a](https://github.com/opera-adt/PROTEUS/pull/15/commits/da0023a82c510ef9fdbe352c12f25d8bd3a7a975), since it puts an implicit requirement on the runconfig to always be relative to the rest of the PGE/SAS structure. I have no issues with supporting the case where the runconfig and input files are all in the same directory, but I don't think we should necessarily be _forced_ to accommodate that layout.
> 
> For example, currently the PGE layer extracts an "isolated" SAS-only version of the runconfig from the full PGE+SAS version. The isolated config is then passed to the SAS main script so the SAS does not need to worry about validating any PGE-specific portions of the config. Currently, the PGE creates this "isolated" version of the Runconfig in the scratch dir, since it's not needed once processing is complete. But with this would mean all other input/output directories would need to go into the scratch dir as well...
> 
> I think the main question here, which is a valid one, is **how should relative paths be treated in a RunConfig**? My assumption was that the paths would be relative to the working directory the PGE/SAS is executed from (`/home/conda`), whereas you would prefer paths to be relative to the runconfig's location on disk. For the time-being, we can work around this by always specifying absolute paths, but I think we'll need agreement on this pretty soon.

Hi @collinss-jpl , thank you so much for your feedback. Placing the runconfig in the same directory as the input files was just an example of why I think the paths could be relative to the runconfig. In that case, it wouldn't matter from where I execute the SAS (since all paths would be relative to the runconfig directory). 

In the case of docker container, I was thinking that one could also use a relative path, e.g., `../input_dir` rather than `input_dir`.

But I don't have a strong opinion on this and I also don't want to cause problems for you or the PGE. So, I guess I should revert changes of [1501983](https://github.com/opera-adt/PROTEUS/pull/15/commits/1501983b84d0556eaa63edc8c8ad2ad0fe8b8ebd) and [7943a98](https://github.com/opera-adt/PROTEUS/pull/15/commits/7943a98cfd9f0cf18f84ffd3e0d0b6a66704fd8e)?
 Notice that if directories are relative to the working directory, we don't need the function `expand_path_and_append_dir()`.

**Comment by gshiroma** [comment]
> [7943a98](https://github.com/opera-adt/PROTEUS/pull/15/commits/7943a98cfd9f0cf18f84ffd3e0d0b6a66704fd8e)?

Sounds good, @collinss-jpl . Thank you again for your comments. I just reverted the changes from those two commits. Please let me know if you have other concerns or comments about this PR.

**Comment by hfattahi** [comment]
Hi @gshiroma,

I see a setup.py so I tried ```python3 setup.py install```, which went through but then running ```dswx_hls.py --help``` gives the error message:

```
dswx_hls.py --help
Traceback (most recent call last):
  File "/home/fattahi/tools/anaconda3/envs/dswx_hls/bin/dswx_hls.py", line 17, in <module>
    from proteus.dswx_hls import (
ModuleNotFoundError: No module named 'proteus'
``` 

would you please update the installation instruction in the readme?

**Comment by hfattahi** [comment]
Thanks @gshiroma this looks great to me. Nice work. I was also able to install and run on the golden dataset. The caveat was the installation instruction. I created the a conda env, and installed all the libraries based on the requirements in the Docker folder and set the environment manually. It would be either document this approach in README or fix setup.py such that PYTHONPATH is defined. As soon as the installation instruction is updated, I will approve and we can merge.

**Comment by gshiroma** [comment]
Thank you so much, @hfattahi . I just updated `setup.py`. It should work now without manually updating your `PYTHONPATH`. Thank you for catching this.

**Comment by hfattahi** [comment]
I just started with a new fresh environment, install python >3.6 (i.e., 3.10.4) and ran "python3 setup.py install". It failed at installing scipy:

```
Best match: scipy 1.8.0
Processing scipy-1.8.0.tar.gz
Writing /tmp/easy_install-p07c17te/scipy-1.8.0/setup.cfg
Running scipy-1.8.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-p07c17te/scipy-1.8.0/egg-dist-tmp-bynbsk7u
/tmp/easy_install-p07c17te/scipy-1.8.0/setup.py:482: UserWarning: Unrecognized setuptools command ('-q bdist_egg --dist-dir /tmp/easy_install-p07c17te/scipy-1.8.0/egg-dist-tmp-bynbsk7u'), proceeding with generating Cython sources and expanding templates
  warnings.warn("Unrecognized setuptools command ('{}'), proceeding with "
Error: 'numpy' must be installed before running the build.

error: Setup script exited with 1
```

**Comment by gshiroma** [comment]
> I just started with a new fresh environment, install python >3.6 (i.e., 3.10.4) and ran "python3 setup.py install". It failed at installing scipy:
> 
> ```
> Best match: scipy 1.8.0
> Processing scipy-1.8.0.tar.gz
> Writing /tmp/easy_install-p07c17te/scipy-1.8.0/setup.cfg
> Running scipy-1.8.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-p07c17te/scipy-1.8.0/egg-dist-tmp-bynbsk7u
> /tmp/easy_install-p07c17te/scipy-1.8.0/setup.py:482: UserWarning: Unrecognized setuptools command ('-q bdist_egg --dist-dir /tmp/easy_install-p07c17te/scipy-1.8.0/egg-dist-tmp-bynbsk7u'), proceeding with generating Cython sources and expanding templates
>   warnings.warn("Unrecognized setuptools command ('{}'), proceeding with "
> Error: 'numpy' must be installed before running the build.
> 
> error: Setup script exited with 1
> ```

Uhm, interesting @hfattahi . Thank you for trying to install it in a new environment.  `numpy` was automatically added as a dependency for my installation (even on a fresh environment). Would you mind adding `numpy` before `scipy` in your `setup.py` and see if the installation goes smooth please?

**Comment by hfattahi** [comment]
And again as I said if I manually install the libraries as:

```
conda install --file docker/requirements.txt
conda install -c conda-forge --file docker/requirements.txt.forge
```
And then install proteous as :
```
python3 setup.py install
```

then things install almost properly. 
The unit test.  But the workflow test fails:
```
>       hls_thresholds = parse_runconfig_file(
            user_runconfig_file = user_runconfig_file, args = args)

test_dswx_hls_workflow.py:55:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
/home/fattahi/tools/anaconda3/envs/dwsx_hls_2/lib/python3.10/site-packages/proteus-0.1-py3.10.egg/proteus/dswx_hls.py:1600: in parse_runconfig_file
    schema = yamale.make_schema(yaml_schema, parser='ruamel')
/home/fattahi/tools/anaconda3/envs/dwsx_hls_2/lib/python3.10/site-packages/yamale/yamale.py:10: in make_schema
    raw_schemas = readers.parse_yaml(path, parser, content=content)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

path = '/home/fattahi/tools/anaconda3/envs/dwsx_hls_2/lib/python3.10/site-packages/proteus-0.1-py3.10.egg/proteus/schemas/dswx_hls.yaml'
parser = 'ruamel', content = None

    def parse_yaml(path=None, parser='pyyaml', content=None):
        try:
            parse = _parsers[parser.lower()]
        except KeyError:
            raise NameError('Parser "' + parser + '" is not supported\nAvailable parsers are listed below:\nPyYAML\nruamel')
        if (path is None and content is None) or (path is not None and content is not None):
            raise TypeError("Pass either path= or content=, not both")
        if path is not None:
>           with open(path) as f:
E           FileNotFoundError: [Errno 2] No such file or directory: '/home/fattahi/tools/anaconda3/envs/dwsx_hls_2/lib/python3.10/site-packages/proteus-0.1-py3.10.egg/proteus/schemas/dswx_hls.yaml'

/home/fattahi/tools/anaconda3/envs/dwsx_hls_2/lib/python3.10/site-packages/yamale/readers/yaml_reader.py:34: FileNotFoundError
```
which I assume is because ```schemas/dswx_hls.yaml``` is not introduced to the yaml file. 

The only way I pass the tests is to manually setup the PATH and PYTHONPATH (i.e., ignoring all what setup.py did):

```
export PROTEUS_HOME=<PATH_TO_CLONED_REPOSITORY>
export PYTHONPATH=${PYTHONPATH}:${PROTEUS_HOME}/src
export PATH=${PATH}:${PROTEUS_HOME}/bin
```

**Comment by hfattahi** [comment]
> > I just started with a new fresh environment, install python >3.6 (i.e., 3.10.4) and ran "python3 setup.py install". It failed at installing scipy:
> > ```
> > Best match: scipy 1.8.0
> > Processing scipy-1.8.0.tar.gz
> > Writing /tmp/easy_install-p07c17te/scipy-1.8.0/setup.cfg
> > Running scipy-1.8.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-p07c17te/scipy-1.8.0/egg-dist-tmp-bynbsk7u
> > /tmp/easy_install-p07c17te/scipy-1.8.0/setup.py:482: UserWarning: Unrecognized setuptools command ('-q bdist_egg --dist-dir /tmp/easy_install-p07c17te/scipy-1.8.0/egg-dist-tmp-bynbsk7u'), proceeding with generating Cython sources and expanding templates
> >   warnings.warn("Unrecognized setuptools command ('{}'), proceeding with "
> > Error: 'numpy' must be installed before running the build.
> > 
> > error: Setup script exited with 1
> > ```
> 
> Uhm, interesting @hfattahi . Thank you for trying to install it in a new environment. `numpy` was automatically added as a dependency for my installation (even on a fresh environment). Would you mind adding `numpy` before `scipy` in your `setup.py` and see if the installation goes smooth please?

numpy is already coming before scipy in setup.py.

**Comment by gshiroma** [comment]
> And again as I said if I manually install the libraries as:
> 
> ```
> conda install --file docker/requirements.txt
> conda install -c conda-forge --file docker/requirements.txt.forge
> ```
> 
> And then install proteous as :
> 
> ```
> python3 setup.py install
> ```
> 
> then things install almost properly. The unit test. But the workflow test fails:
> 
> ```
> >       hls_thresholds = parse_runconfig_file(
>             user_runconfig_file = user_runconfig_file, args = args)
> 
> test_dswx_hls_workflow.py:55:
> _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
> /home/fattahi/tools/anaconda3/envs/dwsx_hls_2/lib/python3.10/site-packages/proteus-0.1-py3.10.egg/proteus/dswx_hls.py:1600: in parse_runconfig_file
>     schema = yamale.make_schema(yaml_schema, parser='ruamel')
> /home/fattahi/tools/anaconda3/envs/dwsx_hls_2/lib/python3.10/site-packages/yamale/yamale.py:10: in make_schema
>     raw_schemas = readers.parse_yaml(path, parser, content=content)
> _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
> 
> path = '/home/fattahi/tools/anaconda3/envs/dwsx_hls_2/lib/python3.10/site-packages/proteus-0.1-py3.10.egg/proteus/schemas/dswx_hls.yaml'
> parser = 'ruamel', content = None
> 
>     def parse_yaml(path=None, parser='pyyaml', content=None):
>         try:
>             parse = _parsers[parser.lower()]
>         except KeyError:
>             raise NameError('Parser "' + parser + '" is not supported\nAvailable parsers are listed below:\nPyYAML\nruamel')
>         if (path is None and content is None) or (path is not None and content is not None):
>             raise TypeError("Pass either path= or content=, not both")
>         if path is not None:
> >           with open(path) as f:
> E           FileNotFoundError: [Errno 2] No such file or directory: '/home/fattahi/tools/anaconda3/envs/dwsx_hls_2/lib/python3.10/site-packages/proteus-0.1-py3.10.egg/proteus/schemas/dswx_hls.yaml'
> 
> /home/fattahi/tools/anaconda3/envs/dwsx_hls_2/lib/python3.10/site-packages/yamale/readers/yaml_reader.py:34: FileNotFoundError
> ```
> 
> which I assume is because `schemas/dswx_hls.yaml` is not introduced to the yaml file.
> 
> The only way I pass the tests is to manually setup the PATH and PYTHONPATH (i.e., ignoring all what setup.py did):
> 
> ```
> export PROTEUS_HOME=<PATH_TO_CLONED_REPOSITORY>
> export PYTHONPATH=${PYTHONPATH}:${PROTEUS_HOME}/src
> export PATH=${PATH}:${PROTEUS_HOME}/bin
> ```

It should work without setting your `PATH` and `PYTHONPATH`. I just added another line. The `FileNotFoundError` should be fixed with this latest commit. I'm just not sure about the `numpy` error.

**Comment by hfattahi** [comment]
@gshiroma for this PR let's update the README with the following instruction for conda at least:
```
clone the repository
conda create -n proteous
conda activate proteous
cd to CLONED_REPO
conda install --file docker/requirements.txt
conda install -c conda-forge --file docker/requirements.txt.forge
python setup.py install

Run the unit and workflow test:
cd tests
pytest -rpP
```
And open an issue that setup.py may be fixed for numpy issue.

**Review by hfattahi — DISMISSED** [review]
Thank you @gshiroma . Great work.

**Comment by gshiroma** [comment]
> Thank you @gshiroma . Great work.

Thank you, @hfattahi !

**Review by collinss-jpl — APPROVED** [review]
Hi @gshiroma, sorry for the late reply, but everything looks good on my end

**Comment by gshiroma** [comment]
> Hi @gshiroma, sorry for the late reply, but everything looks good on my end

Thank you, @collinss-jpl !

**Review by hfattahi — APPROVED** [review]
Thanks again and thanks for taking care of codacy complains.

**Pull request merged**
